### PR TITLE
Add Typescript declarations

### PR DESCRIPTION
**Pull request by dscho**
This benefits not only code using `node-fetch-retry` which is written in Typescript, but thanks to ESLint having learned to incorporate `.d.ts` files in its type checking, this PR benefits _all_ users.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CODE_OF_CONDUCT** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by dscho** [comment]
As recommended in https://github.com/adobe/node-fetch-retry/pull/42/checks?check_run_id=2003116147, I will close and re-open this PR.

**Comment by dscho** [comment]
About https://github.com/adobe/node-fetch-retry/pull/42/checks?check_run_id=2003162863#step:3:6:

> ```
> Run npx @adobe/sizewatcher
> npx: installed 47 in 4.649s
> Checking out git branches...
> Error: error: pathspec 'add-typescript-declarations' did not match any file(s) known to git
> ```

Does this maybe assume the branch not to be in a fork? In any case, the Typescript definition shouldn't increase the size by much 😁

**Comment by dscho** [comment]
Requesting a review from @tmathern and @DrGirlfriend

**Comment by dscho** [comment]
@tmathern @jdelbick what is the verdict? Close without merge? Close after adjustments? It's a bit lonely over here without any review.

**Comment by tmathern** [comment]
@dscho Hello :). Sorry for the delay. 
I don't do a lot of Typescript... So how would I test this? Verify that the interface is correct?

**Comment by dscho** [comment]
>  So how would I test this?

You could build the package and then use it in a tiny Typescript program, something like

```typescript
import fetch from '@adobe/node-fetch-retry'

async function fetchJSONFromURL<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (res.status !== 200) {
    throw new Error(
      `Got code ${res.status}, URL: ${url}, message: ${res.statusText}`
    )
  }
  return (await res.json()) as T
}

class JSONSubset {
  current_user_url: string;
}

(async (): Promise<void> => {
  console.log(JSON.stringify(await fetchJSONFromURL<JSONSubset>('https://api.github.com'));
})().catch(console.log);
```

Then `npm install typescript` and use `node_modules/.bin/tsc` to transpile the script to Javascript.

> Verify that the interface is correct?

Obviously, you don't have to verify `RequestInfo`, `RequestInit`, and `Response` because those come from `node-fetch` directly. But you could verify that `node-fetch-retry` does handle the [`retryOptions`](https://github.com/adobe/node-fetch-retry/blob/daffa3fde5dd260d3e73e0db7a7e508e778bb2c2/index.d.ts#L4-L11) as I declared them, and that [the signature of the `fetch()` function](https://github.com/adobe/node-fetch-retry/blob/daffa3fde5dd260d3e73e0db7a7e508e778bb2c2/index.d.ts#L14-L17) looks correct.

**Comment by dscho** [comment]
@tmathern did that help?

**Comment by dscho** [comment]
FWIW I updated the definition to include `retryOnHttpError`. I needed to update less than I thought, 9½ months later (I think the baby is ready to be induced now).

**Comment by dscho** [comment]
@jdelbick also pinging you ;-)

**Comment by dscho** [comment]
And since the check run still has to be approved, I ran one myself (took a minimal throw-away patch to force CI to run on the `test-run` branch): https://github.com/dscho/node-fetch-retry/runs/4815132242?check_suite_focus=true. All tests pass, of course.

**Review by tmathern — APPROVED** [review]

**Comment by tmathern** [comment]
@jdelbick Could you take a look too?

**Review by jdelbick — APPROVED** [review]

**Comment by dscho** [comment]
@jdelbick anything I need to do about [the `sizewatcher` failure](https://github.com/adobe/node-fetch-retry/runs/4928663130?check_suite_focus=true#step:3:6)?

**Comment by jdelbick** [comment]
@dscho, no, we can safely ignore. It just fails because we added a file but that file doesn't need a test

**Comment by dscho** [comment]
Thank you!

**Comment by tmathern** [comment]
Thanks for the contribution, @dscho!

**Pull request merged**
